import { reactive, ref } from 'vue'
import { useConfigStore } from '@/stores/config'
import { useAdminStore } from '@/stores/admin'

export function useAgentRuntimeConfig() {
  const configStore = useConfigStore(); const adminStore = useAdminStore()
  const agentDraft = reactive({ ...configStore.cfg.agent }); const behaviorSaving = ref(false); const behaviorSaved = ref(false); const behaviorError = ref('')
  function resetBehavior() { Object.assign(agentDraft, configStore.cfg.agent) }
  async function saveBehavior() { behaviorSaving.value = true; behaviorSaved.value = false; behaviorError.value = ''; try { await configStore.saveConfig({ agent: { ...agentDraft } }); behaviorSaved.value = true; setTimeout(() => { behaviorSaved.value = false }, 3000) } catch (e) { behaviorError.value = e instanceof Error ? e.message : String(e) } finally { behaviorSaving.value = false } }
  const generalSearchDraft = reactive({ tavily_api_key: configStore.cfg.search.tavily_api_key, searxng_url: configStore.cfg.search.searxng_url, searxng_engines: configStore.cfg.search.searxng_engines, searxng_image_engines: configStore.cfg.search.searxng_image_engines, max_results: configStore.cfg.search.max_results, global_search_backend: configStore.cfg.search.global_search_backend, rust_lexical_backend: configStore.cfg.search.rust_lexical_backend })
  const similarImageDraft = reactive({ similar_image_enabled: configStore.cfg.search.similar_image_enabled, baidu_qianfan_api_key: configStore.cfg.search.baidu_qianfan_api_key, similar_image_default_count: configStore.cfg.search.similar_image_default_count, similar_image_timeout_seconds: configStore.cfg.search.similar_image_timeout_seconds, similar_image_limit_daily: configStore.cfg.search.similar_image_limit_daily })
  const generalSearchSaving = ref(false); const generalSearchSaved = ref(false); const generalSearchError = ref(''); const similarImageSaving = ref(false); const similarImageSaved = ref(false); const similarImageError = ref('')
  function resetGeneralSearch() { Object.assign(generalSearchDraft, { tavily_api_key: configStore.cfg.search.tavily_api_key, searxng_url: configStore.cfg.search.searxng_url, searxng_engines: configStore.cfg.search.searxng_engines, searxng_image_engines: configStore.cfg.search.searxng_image_engines, max_results: configStore.cfg.search.max_results, global_search_backend: configStore.cfg.search.global_search_backend, rust_lexical_backend: configStore.cfg.search.rust_lexical_backend }) }
  function resetSimilarImageSearch() { Object.assign(similarImageDraft, { similar_image_enabled: configStore.cfg.search.similar_image_enabled, baidu_qianfan_api_key: configStore.cfg.search.baidu_qianfan_api_key, similar_image_default_count: configStore.cfg.search.similar_image_default_count, similar_image_timeout_seconds: configStore.cfg.search.similar_image_timeout_seconds, similar_image_limit_daily: configStore.cfg.search.similar_image_limit_daily }) }
  const voiceDraft = reactive({ ...configStore.cfg.voice }); const voiceSaving = ref(false); const voiceSaved = ref(false); const voiceError = ref(''); const voiceTesting = ref(false); const voiceTestMsg = ref('')
  const VOICE_API_FORMATS = [{ value: 'openai', label: 'OpenAI 兼容' }, { value: 'dashscope', label: '百炼 DashScope' }]
  const VOICE_DASHSCOPE_SERVICES = [{ value: 'qwen3-asr', label: 'Qwen3 ASR · qwen3-asr-flash' }, { value: 'qwen-audio', label: 'Qwen-Audio 3.0 · qwen-audio-3.0-asr-flash' }, { value: 'fun-asr', label: 'Fun-ASR · fun-asr-flash-2026-06-15' }]
  function resetVoice() { Object.assign(voiceDraft, configStore.cfg.voice) }
  function setDashscopeService(value: string) { voiceDraft.dashscope_service = value; voiceDraft.model = ({ 'qwen3-asr': 'qwen3-asr-flash', 'qwen-audio': 'qwen-audio-3.0-asr-flash', 'fun-asr': 'fun-asr-flash-2026-06-15' } as Record<string, string>)[value] || '' }
  async function saveVoice() { voiceSaving.value = true; voiceSaved.value = false; voiceError.value = ''; try { await configStore.saveConfig({ voice: { ...voiceDraft } }); voiceSaved.value = true; Object.assign(voiceDraft, configStore.cfg.voice); setTimeout(() => { voiceSaved.value = false }, 3000) } catch (e) { voiceError.value = e instanceof Error ? e.message : String(e) } finally { voiceSaving.value = false } }
  async function testVoice() { voiceTesting.value = true; voiceError.value = ''; voiceTestMsg.value = ''; try { const res = await adminStore.authFetch('/api/v1/admin/config/test-voice', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ api_format: voiceDraft.api_format, dashscope_service: voiceDraft.dashscope_service, base_url: voiceDraft.base_url, api_key: voiceDraft.api_key, model: voiceDraft.model }) }); const data = await res.json().catch(() => ({})); if (!res.ok || !data.ok) throw new Error(data.message || `测试失败（${res.status}）`); voiceTestMsg.value = data.message || '语音模型连接正常' } catch (e) { voiceError.value = e instanceof Error ? e.message : String(e) } finally { voiceTesting.value = false } }
  const embeddingDraft = reactive({ ...configStore.cfg.embedding }); const embeddingSaving = ref(false); const embeddingSaved = ref(false); const embeddingError = ref(''); const embTest = reactive({ loading: false, ok: false, msg: '' })
  function resetEmbedding() { Object.assign(embeddingDraft, configStore.cfg.embedding) }
  async function saveEmbedding() { embeddingSaving.value = true; embeddingSaved.value = false; embeddingError.value = ''; try { await configStore.saveConfig({ embedding: { ...embeddingDraft } }); embeddingSaved.value = true; Object.assign(embeddingDraft, configStore.cfg.embedding); setTimeout(() => { embeddingSaved.value = false }, 3000) } catch (e) { embeddingError.value = e instanceof Error ? e.message : String(e) } finally { embeddingSaving.value = false } }
  async function testEmbedding() { embTest.loading = true; embTest.msg = ''; try { const res = await adminStore.authFetch('/api/v1/admin/config/test-embedding', { method: 'POST', body: JSON.stringify({ provider: embeddingDraft.provider || '', multimodal: !!embeddingDraft.multimodal, base_url: embeddingDraft.base_url || '', api_key: embeddingDraft.api_key || '', model: embeddingDraft.model || '', dimensions: embeddingDraft.dimensions || 0 }) }); const data = await res.json(); embTest.ok = !!data.ok; embTest.msg = data.message || (data.ok ? 'OK' : '失败') } catch (e) { embTest.ok = false; embTest.msg = `请求失败：${e instanceof Error ? e.message : String(e)}` } finally { embTest.loading = false } }
  const searchTest = reactive({ searxng: { loading: false, ok: false, msg: '' }, searxng_images: { loading: false, ok: false, msg: '' }, tavily: { loading: false, ok: false, msg: '' }, baidu_similar_images: { loading: false, ok: false, msg: '' } })
  async function testSearch(target: keyof typeof searchTest) { const state = searchTest[target]; state.loading = true; state.msg = ''; try { const payload = target === 'tavily' ? { target, tavily_api_key: generalSearchDraft.tavily_api_key || '' } : target === 'baidu_similar_images' ? { target, baidu_qianfan_api_key: similarImageDraft.baidu_qianfan_api_key || '' } : target === 'searxng_images' ? { target, searxng_url: generalSearchDraft.searxng_url || '', searxng_image_engines: generalSearchDraft.searxng_image_engines || '' } : { target, searxng_url: generalSearchDraft.searxng_url || '', searxng_engines: generalSearchDraft.searxng_engines || '' }; const res = await adminStore.authFetch('/api/v1/admin/config/test-search', { method: 'POST', body: JSON.stringify(payload) }); const data = await res.json(); state.ok = !!data.ok; state.msg = data.message || (data.ok ? 'OK' : '失败') } catch (e) { state.ok = false; state.msg = `请求失败：${e instanceof Error ? e.message : String(e)}` } finally { state.loading = false } }
  async function saveSearch(source: 'general' | 'similar') { const similar = source === 'similar'; const saving = similar ? similarImageSaving : generalSearchSaving; const saved = similar ? similarImageSaved : generalSearchSaved; const error = similar ? similarImageError : generalSearchError; saving.value = true; saved.value = false; error.value = ''; try { await configStore.saveConfig({ search: similar ? { ...similarImageDraft } : { ...generalSearchDraft } }); saved.value = true; if (similar) resetSimilarImageSearch(); else resetGeneralSearch(); setTimeout(() => { saved.value = false }, 3000) } catch (e) { error.value = e instanceof Error ? e.message : String(e) } finally { saving.value = false } }
  return { configStore, agentDraft, behaviorSaving, behaviorSaved, behaviorError, resetBehavior, saveBehavior, generalSearchDraft, similarImageDraft, generalSearchSaving, generalSearchSaved, generalSearchError, similarImageSaving, similarImageSaved, similarImageError, resetGeneralSearch, resetSimilarImageSearch, voiceDraft, voiceSaving, voiceSaved, voiceError, voiceTesting, voiceTestMsg, VOICE_API_FORMATS, VOICE_DASHSCOPE_SERVICES, resetVoice, setDashscopeService, saveVoice, testVoice, embeddingDraft, embeddingSaving, embeddingSaved, embeddingError, embTest, resetEmbedding, saveEmbedding, testEmbedding, searchTest, testSearch, saveSearch }
}
