type LocaleMessages = Record<string, any>

export function applyAdminAgentSection(messages: Record<'zh-CN' | 'ja-JP' | 'en-US', LocaleMessages>) {
  Object.assign((messages['zh-CN'] as Record<string, any>).adminAgentUi, { loadFailed: '加载失败：{message}', operationFailed: '设置失败', strategyPool: '已切到多 key 分流（勾选要参与分流的预设）', strategyRouter: '已切到智能路由（待 Router 接入，暂等同单一激活）', strategyActive: '已切到单一激活', strategyFailed: '切换策略失败：{message}', routingUpdated: '分流方式已更新', routingFailed: '设置分流方式失败：{message}', concurrencySaved: '并发量已设为 {value}（worker ≤30s 热生效）', concurrencyFailed: '保存并发量失败：{message}', switchFailed: '切换失败（{status}）', switched: '已切换，即时生效', deletePresetTitle: '删除模型预设', deletePresetMessage: '确定删除该预设？', deletePresetConfirm: '删除预设', connectionOk: '连通正常（{status}）', connectionFailed: '连接失败（{status}）：{detail}', testFailed: '测试失败：{message}' })
  Object.assign((messages['ja-JP'] as Record<string, any>).adminAgentUi, { loadFailed: '読み込みに失敗：{message}', operationFailed: '設定に失敗しました', strategyPool: 'キー分散に切り替えました（参加するプリセットを選択）', strategyRouter: 'スマートルーティングに切り替えました（Router 接続待ち）', strategyActive: '単一アクティブに切り替えました', strategyFailed: '戦略の切り替えに失敗：{message}', routingUpdated: '分散方式を更新しました', routingFailed: '分散方式の設定に失敗：{message}', concurrencySaved: '同時実行数を {value} に設定しました（worker は30秒以内に反映）', concurrencyFailed: '同時実行数の保存に失敗：{message}', switchFailed: '切り替えに失敗（{status}）', switched: '切り替えました。すぐに反映されます', deletePresetTitle: 'モデルプリセットを削除', deletePresetMessage: 'このプリセットを削除しますか？', deletePresetConfirm: 'プリセットを削除', connectionOk: '接続成功（{status}）', connectionFailed: '接続失敗（{status}）：{detail}', testFailed: 'テストに失敗：{message}' })
  Object.assign((messages['en-US'] as Record<string, any>).adminAgentUi, { loadFailed: 'Load failed: {message}', operationFailed: 'Operation failed', strategyPool: 'Switched to key pooling (select presets to include)', strategyRouter: 'Switched to smart routing (Router integration pending)', strategyActive: 'Switched to single active', strategyFailed: 'Failed to switch strategy: {message}', routingUpdated: 'Routing mode updated', routingFailed: 'Failed to update routing mode: {message}', concurrencySaved: 'Concurrency set to {value} (worker applies within 30s)', concurrencyFailed: 'Failed to save concurrency: {message}', switchFailed: 'Switch failed ({status})', switched: 'Switched; effective immediately', deletePresetTitle: 'Delete model preset', deletePresetMessage: 'Delete this preset?', deletePresetConfirm: 'Delete preset', connectionOk: 'Connection OK ({status})', connectionFailed: 'Connection failed ({status}): {detail}', testFailed: 'Test failed: {message}' })
  Object.assign((messages['zh-CN'] as Record<string, any>).adminAgentUi, { providerOpenai: 'OpenAI 兼容', providerAnthropic: 'Anthropic 兼容', providerQwen: '通义千问', providerGlm: '智谱 GLM', providerDeepseek: 'DeepSeek', providerMinimax: 'MiniMax', providerMimo: 'MiMo', providerOllama: 'Ollama', providerLocal: '本地兼容服务', formatOpenai: 'OpenAI 格式', formatAnthropic: 'Anthropic 兼容', imageHint: '用户发的图片直接给模型「看」', videoHint: '用户发的视频直接给模型「看」', audioHint: '用户发的音频直接给模型「听」', defaultOption: '默认', low: '低', high: '高', maximum: '最大', auto: '自动', original: '原图', generalApi: '通用 API', codingPlan: 'Coding Plan', otherCompatible: '其它兼容服务', localOllama: '本地 Ollama', ollamaNative: 'Ollama 原生', capabilityProbeFailed: '能力检测失败', modelsLoadFailed: '获取模型列表失败', modelsEmpty: '提供商没有返回可用模型，请手动输入', saveFailedStatus: '保存失败（{status}）', saved: '已保存', dimensionSupported: '{label}：支持，已开启', dimensionUnsupported: '{label}：不支持，已设为关闭：{detail}', dimensionUnknown: '{label}：测不准：{detail}', supportedList: '支持：{values}', unsupportedList: '不支持：{values}', unknownList: '测不准：{values}', probeComplete: '检测完成 — {details}', probeNoResult: '检测完成，未返回结果', probeFailed: '检测失败：{message}' })
  Object.assign((messages['ja-JP'] as Record<string, any>).adminAgentUi, { providerOpenai: 'OpenAI 互換', providerAnthropic: 'Anthropic 互換', providerQwen: '通義千問', providerGlm: '智譜 GLM', providerDeepseek: 'DeepSeek', providerMinimax: 'MiniMax', providerMimo: 'MiMo', providerOllama: 'Ollama', providerLocal: 'ローカル互換サービス', formatOpenai: 'OpenAI 形式', formatAnthropic: 'Anthropic 互換', imageHint: 'ユーザーの画像をモデルに直接渡します', videoHint: 'ユーザーの動画をモデルに直接渡します', audioHint: 'ユーザーの音声をモデルに直接渡します', defaultOption: 'デフォルト', low: '低', high: '高', maximum: '最大', auto: '自動', original: '原画像', generalApi: '汎用 API', codingPlan: 'Coding Plan', otherCompatible: 'その他の互換サービス', localOllama: 'ローカル Ollama', ollamaNative: 'Ollama ネイティブ', capabilityProbeFailed: '機能検出に失敗しました', modelsLoadFailed: 'モデル一覧の取得に失敗しました', modelsEmpty: 'Provider から利用可能なモデルが返りませんでした。手動で入力してください', saveFailedStatus: '保存に失敗（{status}）', saved: '保存しました', dimensionSupported: '{label}：対応、オンにしました', dimensionUnsupported: '{label}：非対応、オフにしました：{detail}', dimensionUnknown: '{label}：判定できません：{detail}', supportedList: '対応：{values}', unsupportedList: '非対応：{values}', unknownList: '判定不能：{values}', probeComplete: '検出完了 — {details}', probeNoResult: '検出完了、結果なし', probeFailed: '検出に失敗：{message}' })
  Object.assign((messages['en-US'] as Record<string, any>).adminAgentUi, { providerOpenai: 'OpenAI compatible', providerAnthropic: 'Anthropic compatible', providerQwen: 'Qwen', providerGlm: 'GLM', providerDeepseek: 'DeepSeek', providerMinimax: 'MiniMax', providerMimo: 'MiMo', providerOllama: 'Ollama', providerLocal: 'Local compatible service', formatOpenai: 'OpenAI format', formatAnthropic: 'Anthropic compatible', imageHint: 'Pass user images directly to the model', videoHint: 'Pass user videos directly to the model', audioHint: 'Pass user audio directly to the model', defaultOption: 'Default', low: 'Low', high: 'High', maximum: 'Maximum', auto: 'Auto', original: 'Original', generalApi: 'General API', codingPlan: 'Coding Plan', otherCompatible: 'Other compatible service', localOllama: 'Local Ollama', ollamaNative: 'Ollama native', capabilityProbeFailed: 'Capability detection failed', modelsLoadFailed: 'Failed to load model list', modelsEmpty: 'The provider returned no available models; enter one manually', saveFailedStatus: 'Save failed ({status})', saved: 'Saved', dimensionSupported: '{label}: supported and enabled', dimensionUnsupported: '{label}: unsupported and disabled: {detail}', dimensionUnknown: '{label}: could not determine support: {detail}', supportedList: 'Supported: {values}', unsupportedList: 'Unsupported: {values}', unknownList: 'Unknown: {values}', probeComplete: 'Detection complete — {details}', probeNoResult: 'Detection complete; no result returned', probeFailed: 'Detection failed: {message}' })
  Object.assign((messages['zh-CN'] as Record<string, any>).adminAgentUi, { loadFailedStatus: '加载失败（{status}）', loadRetry: '加载失败，请重试', saveFailed: '保存失败', saveRetry: '保存失败，请重试' })
  Object.assign((messages['ja-JP'] as Record<string, any>).adminAgentUi, { loadFailedStatus: '読み込みに失敗（{status}）', loadRetry: '読み込みに失敗しました。再試行してください', saveFailed: '保存に失敗しました', saveRetry: '保存に失敗しました。再試行してください' })
  Object.assign((messages['en-US'] as Record<string, any>).adminAgentUi, { loadFailedStatus: 'Load failed ({status})', loadRetry: 'Load failed; please retry', saveFailed: 'Save failed', saveRetry: 'Save failed; please retry' })
  Object.assign((messages['zh-CN'] as Record<string, any>).adminAgentUi, { capabilityLoadFailedStatus: '加载能力目录失败（{status}）', capabilityLoadFailed: '加载能力目录失败' })
  Object.assign((messages['ja-JP'] as Record<string, any>).adminAgentUi, { capabilityLoadFailedStatus: '機能一覧の読み込みに失敗（{status}）', capabilityLoadFailed: '機能一覧の読み込みに失敗しました' })
  Object.assign((messages['en-US'] as Record<string, any>).adminAgentUi, { capabilityLoadFailedStatus: 'Failed to load capability catalog ({status})', capabilityLoadFailed: 'Failed to load capability catalog' })
  Object.assign((messages['zh-CN'] as Record<string, any>).adminAgentUi, { probeCompleteLabel: '多模态检测完成' })
  Object.assign((messages['ja-JP'] as Record<string, any>).adminAgentUi, { probeCompleteLabel: 'マルチモーダル検出完了' })
  Object.assign((messages['en-US'] as Record<string, any>).adminAgentUi, { probeCompleteLabel: 'Multimodal detection complete' })
}
