export const adminEmailUi = {
  'zh-CN': {
    title: '邮件发布', description: '使用咕咕统一邮件模板编辑、预览并发送站点邮件。', subscribed: '已订阅更新邮件', refreshCount: '刷新人数', content: '邮件内容', template: '模板', subject: '主题行', titleLabel: '邮件标题', preheader: '摘要', subjectPlaceholder: '邮件主题', titlePlaceholder: '收件人看到的主标题', preheaderPlaceholder: '列表预览摘要（可选）', body: '正文', bodyPlaceholder: '输入邮件正文，预览会同步更新', theme: '主题', light: '亮色', dark: '暗色', palette: '配色', add: '＋添加', contentBlocks: '内容区块', actions: '操作按钮', delete: '删除', sectionHeadingPlaceholder: '区块标题（可选）', sectionTextPlaceholder: '区块内容', actionLabelPlaceholder: '按钮文字', urlPlaceholder: 'https://example.com', detail: '查看详情', translate: '一键生成多语言', translating: '生成中…', languages: { 'zh-CN': '简体中文', 'ja-JP': '日本語', 'en-US': 'English' }, sendTest: '发送测试', sending: '发送中…', testRecipient: '测试收件人邮箱', testHint: '测试邮件使用系统 SMTP，仅发送到上方填写的地址。', publishHint: '正式发布将按用户界面语言发送给 {count} 位已订阅用户', publish: '发布给已订阅用户', queued: '已提交…', preview: '实时预览', refreshPreview: '刷新预览', previewTitle: '邮件预览', confirmTitle: '确认发布邮件', confirmMessage: '将按用户界面语言向 {count} 位已订阅用户发送这封邮件。邮件提交后无法撤回，确定继续吗？', confirmPublish: '确认发布', previewFailed: '预览失败', countFailed: '无法读取收件人数', fillRecipient: '请填写测试收件人邮箱', testFailed: '测试邮件发送失败', testSubmitted: '测试邮件已提交给 SMTP', publishFailed: '邮件发布失败', publishSuccess: '邮件已加入发送队列，共 {count} 位收件人', translationFailed: '多语言邮件生成失败', noRecipients: '没有可发送的订阅用户',
  },
  'ja-JP': {
    title: 'メール配信', description: 'Gugu 共通テンプレートでサイトメールを編集、プレビュー、配信します。', subscribed: '更新メール購読者', refreshCount: '人数を更新', content: 'メール内容', template: 'テンプレート', subject: '件名', titleLabel: 'メールタイトル', preheader: '概要', subjectPlaceholder: 'メール件名', titlePlaceholder: '受信者に表示する見出し', preheaderPlaceholder: '一覧プレビュー（任意）', body: '本文', bodyPlaceholder: 'メール本文を入力するとプレビューに反映されます', theme: 'テーマ', light: 'ライト', dark: 'ダーク', palette: '配色', add: '＋追加', contentBlocks: '内容ブロック', actions: 'アクションボタン', delete: '削除', sectionHeadingPlaceholder: 'ブロック見出し（任意）', sectionTextPlaceholder: 'ブロック内容', actionLabelPlaceholder: 'ボタン文字', urlPlaceholder: 'https://example.com', detail: '詳細を見る', translate: '多言語を一括生成', translating: '生成中…', languages: { 'zh-CN': '简体中文', 'ja-JP': '日本語', 'en-US': 'English' }, sendTest: 'テスト送信', sending: '送信中…', testRecipient: 'テスト受信者メール', testHint: 'システム SMTP を使用し、上のアドレスだけに送信します。', publishHint: 'ユーザーの表示言語に合わせて {count} 人の購読者へ配信', publish: '購読者へ配信', queued: '送信待ち…', preview: 'リアルタイムプレビュー', refreshPreview: 'プレビューを更新', previewTitle: 'メールプレビュー', confirmTitle: 'メール配信の確認', confirmMessage: 'ユーザーの表示言語に合わせて {count} 人の購読者へ配信します。取り消せません。続行しますか？', confirmPublish: '配信を確認', previewFailed: 'プレビューに失敗しました', countFailed: '購読者数を取得できません', fillRecipient: 'テスト受信者メールを入力してください', testFailed: 'テスト送信に失敗しました', testSubmitted: 'テストメールを SMTP に送信しました', publishFailed: 'メール配信に失敗しました', publishSuccess: '{count} 人を送信キューに追加しました', translationFailed: '多言語メールの生成に失敗しました', noRecipients: '配信対象の購読者はいません',
  },
  'en-US': {
    title: 'Publish email', description: 'Edit, preview, and send site emails with Gugu’s shared template.', subscribed: 'Update subscribers', refreshCount: 'Refresh count', content: 'Email content', template: 'Template', subject: 'Subject line', titleLabel: 'Email title', preheader: 'Preheader', subjectPlaceholder: 'Email subject', titlePlaceholder: 'Main heading shown to recipients', preheaderPlaceholder: 'List preview (optional)', body: 'Body', bodyPlaceholder: 'Enter the email body; the preview updates automatically', theme: 'Theme', light: 'Light', dark: 'Dark', palette: 'Palette', add: '＋Add', contentBlocks: 'Content blocks', actions: 'Action buttons', delete: 'Delete', sectionHeadingPlaceholder: 'Block heading (optional)', sectionTextPlaceholder: 'Block content', actionLabelPlaceholder: 'Button label', urlPlaceholder: 'https://example.com', detail: 'View details', translate: 'Generate translations', translating: 'Generating…', languages: { 'zh-CN': '简体中文', 'ja-JP': '日本語', 'en-US': 'English' }, sendTest: 'Send test', sending: 'Sending…', testRecipient: 'Test recipient email', testHint: 'The test uses system SMTP and only sends to the address above.', publishHint: 'Send to {count} subscribed users using their interface language', publish: 'Publish to subscribers', queued: 'Queued…', preview: 'Live preview', refreshPreview: 'Refresh preview', previewTitle: 'Email preview', confirmTitle: 'Confirm email publish', confirmMessage: 'This will send to {count} subscribed users in their interface languages. It cannot be recalled. Continue?', confirmPublish: 'Confirm publish', previewFailed: 'Preview failed', countFailed: 'Unable to read subscriber count', fillRecipient: 'Enter a test recipient email', testFailed: 'Test email failed', testSubmitted: 'Test email submitted to SMTP', publishFailed: 'Email publish failed', publishSuccess: 'Added {count} recipients to the send queue', translationFailed: 'Translation generation failed', noRecipients: 'There are no subscribed recipients',
  },
} as const
