export const configUi = {
  'zh-CN': { feedbackTitle: '用户反馈邮件', feedbackHint: '收到 Bug、建议或其他反馈时，发送提醒到支持邮箱', securityTitle: '安全告警', securityHint: '重复越权访问触发限流或冻结时发送脱敏邮箱通知', enabled: '开启', disabled: '关闭', supportEmail: '支持邮箱', smtpRequired: '需要先配置上方邮件系统的 SMTP 服务器；关闭后反馈仍会保存。', alertEmail: '告警目标邮箱', alertEmailPlaceholder: "security{'@'}example.com，多个邮箱用逗号分隔", invalidEmail: '邮箱格式无效：{emails}', privacyHint: '只发送事件类型、动作和聚合次数，不包含资源、IP、Token 或正文' },
  'ja-JP': { feedbackTitle: 'ユーザーフィードバックメール', feedbackHint: 'バグや提案を受け取ったとき、サポートメールへ通知します', securityTitle: 'セキュリティ警告', securityHint: '繰り返しの権限外アクセスで制限または凍結した際に、匿名化したメールを送信します', enabled: '有効', disabled: '無効', supportEmail: 'サポートメール', smtpRequired: '先に上のメールシステムで SMTP サーバーを設定してください。無効でもフィードバックは保存されます。', alertEmail: '警告通知先メール', alertEmailPlaceholder: "security{'@'}example.com、複数のメールはカンマ区切り", invalidEmail: 'メール形式が無効です：{emails}', privacyHint: 'イベント種別、操作、集計数のみ送信し、リソース、IP、Token、本文は含めません' },
  'en-US': { feedbackTitle: 'Feedback email', feedbackHint: 'Send a reminder to the support mailbox when users submit bugs or suggestions', securityTitle: 'Security alerts', securityHint: 'Send a redacted email when repeated unauthorized access triggers throttling or suspension', enabled: 'Enabled', disabled: 'Disabled', supportEmail: 'Support email', smtpRequired: 'Configure the SMTP server above first; feedback is still saved when disabled.', alertEmail: 'Alert recipient email', alertEmailPlaceholder: "security{'@'}example.com, separate multiple addresses with commas", invalidEmail: 'Invalid email format: {emails}', privacyHint: 'Only event type, action, and aggregate count are sent; no resource, IP, Token, or body' },
} as const
export const configExtraUi = {
  'zh-CN': { database: '数据库', postgresHint: 'PostgreSQL 连接配置', redis: 'Redis 缓存', redisHint: '会话缓存与实时任务队列', host: '主机', port: '端口', databaseName: '数据库名', username: '用户名', password: '密码', keepUnchanged: '留空表示不修改', test: '测试连接', testing: '测试中…', init: '初始化数据库', initializing: '初始化中…', initTitle: '重置连接 + 重建所有表（幂等）', globalSearch: '站内全局搜索', globalSearchHint: '选择站内数据的搜索后端；不影响 Agent 的联网搜索。', persistentIndex: '持久化索引（BM25）', ilike: 'ILIKE 兼容模式', searchLabel: '站内全局搜索后端', searchHint: 'BM25 持久化搜索适合稳定检索；ILIKE 兼容模式无需索引维护。', fileStorage: '文件存储', fileStorageHint: '上传文件的存放位置', localDisk: '本地磁盘', aliyunOss: '阿里云 OSS', bucketName: 'Bucket 名', storagePath: '存储路径', objectPrefix: '对象前缀', optionalSuffix: '（选填）', testOss: '测试 OSS 连接', mailSystem: '邮件系统', mailHint: 'SMTP 发信配置，用于用户反馈邮件提醒', ssl: 'SSL（端口 465）', starttls: 'STARTTLS（端口 587）', smtpServer: 'SMTP 服务器', account: '登录账号', loginPassword: '登录密码', sender: '发件人地址', senderKeep: '留空则同登录账号', testRecipient: '测试收件人', sendTest: '测试发送', sending: '发送中…', saveHint: '密码留空表示不修改，填写新值则覆盖', undo: '撤销修改' },
  'ja-JP': { database: 'データベース', postgresHint: 'PostgreSQL 接続設定', redis: 'Redis キャッシュ', redisHint: 'セッションキャッシュとリアルタイムタスクキュー', host: 'ホスト', port: 'ポート', databaseName: 'データベース名', username: 'ユーザー名', password: 'パスワード', keepUnchanged: '空欄＝変更なし', test: '接続テスト', testing: 'テスト中…', init: 'データベースを初期化', initializing: '初期化中…', initTitle: '接続をリセットして全テーブルを再構築（冪等）', globalSearch: 'サイト内グローバル検索', globalSearchHint: 'サイト内データの検索バックエンドを選択します。Agent のウェブ検索には影響しません。', persistentIndex: '永続インデックス（BM25）', ilike: 'ILIKE 互換モード', searchLabel: 'サイト内グローバル検索バックエンド', searchHint: '永続 BM25 は安定した検索に適し、ILIKE 互換モードはインデックス管理が不要です。', fileStorage: 'ファイルストレージ', fileStorageHint: 'アップロードファイルの保存場所', localDisk: 'ローカルディスク', aliyunOss: 'Alibaba Cloud OSS', bucketName: 'Bucket 名', storagePath: '保存先パス', objectPrefix: 'オブジェクトプレフィックス', optionalSuffix: '（任意）', testOss: 'OSS 接続をテスト', mailSystem: 'メールシステム', mailHint: 'ユーザーフィードバック通知用の SMTP 送信設定', ssl: 'SSL（ポート 465）', starttls: 'STARTTLS（ポート 587）', smtpServer: 'SMTP サーバー', account: 'ログインアカウント', loginPassword: 'ログインパスワード', sender: '送信元アドレス', senderKeep: '空欄ならログインアカウントを使用', sendTest: '送信テスト', sending: '送信中…', saveHint: 'パスワードを空欄にすると変更せず、新しい値で上書きします', undo: '変更を取り消す' },
  'en-US': { database: 'Database', postgresHint: 'PostgreSQL connection settings', redis: 'Redis cache', redisHint: 'Session cache and real-time task queue', host: 'Host', port: 'Port', databaseName: 'Database name', username: 'Username', password: 'Password', keepUnchanged: 'Leave blank to keep unchanged', test: 'Test connection', testing: 'Testing…', init: 'Initialize database', initializing: 'Initializing…', initTitle: 'Reset connection and rebuild all tables (idempotent)', globalSearch: 'Global search', globalSearchHint: 'Choose the search backend for site data; this does not affect Agent web search.', persistentIndex: 'Persistent index (BM25)', ilike: 'ILIKE compatibility mode', searchLabel: 'Global search backend', searchHint: 'Persistent BM25 is suitable for stable retrieval; ILIKE mode requires no index maintenance.', fileStorage: 'File storage', fileStorageHint: 'Where uploaded files are stored', localDisk: 'Local disk', aliyunOss: 'Alibaba Cloud OSS', bucketName: 'Bucket name', storagePath: 'Storage path', objectPrefix: 'Object prefix', optionalSuffix: '(optional)', testOss: 'Test OSS connection', mailSystem: 'Mail system', mailHint: 'SMTP sending settings for user feedback notifications', ssl: 'SSL (port 465)', starttls: 'STARTTLS (port 587)', smtpServer: 'SMTP server', account: 'Login account', loginPassword: 'Login password', sender: 'Sender address', senderKeep: 'Leave blank to use the login account', sendTest: 'Send test', sending: 'Sending…', saveHint: 'Leave the password blank to keep it unchanged; enter a new value to overwrite it', undo: 'Undo changes' },
} as const
Object.assign(configExtraUi['ja-JP'], { testRecipient: 'テスト受信者' })
Object.assign(configExtraUi['en-US'], { testRecipient: 'Test recipient' })
