export const filesUi = {
  'zh-CN': { uploadTitle: '上传文件', dropOr: '拖入文件，或', choose: '点击选择', supported: '支持 PSD · PDF · ZIP · PNG 等任意格式', remove: '移除', addMore: '继续添加文件', putInProject: '放入项目', optional: '选填', unlinked: '不关联', pending: '待开始', active: '进行中', done: '已完成', undated: '未设置日期', noProjects: '暂无项目，将以未分类形式上传', uploadLocation: '上传位置', putInFolder: '放入文件夹', root: '项目根目录', noFolders: '暂无文件夹，文件将放在项目根目录', currentFolder: '当前文件夹', stage: '阶段标签', unmarked: '不标记', cancel: '取消', uploading: '上传中…', confirmUpload: '确认上传', folderType: '文件夹', itemCount: '{count} 项', downloadZip: '下载为 ZIP', removeFromCanvas: '从画布移除', deletedSnapshot: '已删除，仅保留快照', personalFiles: '个人文件', projectFiles: '项目文件', trash: '回收站', year: '{year} 年', month: '{month} 月' },
  'ja-JP': { uploadTitle: 'ファイルをアップロード', dropOr: 'ファイルをドロップ、または', choose: '選択', supported: 'PSD・PDF・ZIP・PNG など任意の形式に対応', remove: '削除', addMore: 'ファイルを追加', putInProject: 'プロジェクトに追加', optional: '任意', unlinked: '関連付けない', pending: '未開始', active: '進行中', done: '完了', undated: '日付なし', noProjects: 'プロジェクトがありません。未分類としてアップロードします', uploadLocation: 'アップロード先', putInFolder: 'フォルダーに追加', root: 'プロジェクト直下', noFolders: 'フォルダーがありません。プロジェクト直下に保存します', currentFolder: '現在のフォルダー', stage: 'ステージタグ', unmarked: 'タグなし', cancel: 'キャンセル', uploading: 'アップロード中…', confirmUpload: 'アップロードを確定', folderType: 'フォルダー', itemCount: '{count} 件', downloadZip: 'ZIP をダウンロード', removeFromCanvas: 'キャンバスから削除', deletedSnapshot: '削除済み、スナップショットのみ保持', personalFiles: '個人ファイル', projectFiles: 'プロジェクトファイル', trash: 'ごみ箱', year: '{year} 年', month: '{month} 月' },
  'en-US': { uploadTitle: 'Upload files', dropOr: 'Drop files here, or', choose: 'choose files', supported: 'PSD · PDF · ZIP · PNG and other formats supported', remove: 'Remove', addMore: 'Add more files', putInProject: 'Add to project', optional: 'Optional', unlinked: 'No project', pending: 'Not started', active: 'In progress', done: 'Completed', undated: 'No date', noProjects: 'No projects; files will be uploaded as unclassified', uploadLocation: 'Upload location', putInFolder: 'Add to folder', root: 'Project root', noFolders: 'No folders; files will be placed in the project root', currentFolder: 'Current folder', stage: 'Stage tag', unmarked: 'No tag', cancel: 'Cancel', uploading: 'Uploading…', confirmUpload: 'Confirm upload', folderType: 'Folder', itemCount: '{count} items', downloadZip: 'Download as ZIP', removeFromCanvas: 'Remove from canvas', deletedSnapshot: 'Deleted; snapshot retained', personalFiles: 'Personal files', projectFiles: 'Project files', trash: 'Trash', year: '{year}', month: '{month}' },
} as const

Object.assign(filesUi['zh-CN'], {
  compress: '压缩', extract: '解压', archiveCompressTitle: '压缩所选内容', archiveExtractTitle: '解压文件',
  archiveCompressHint: '所选文件与文件夹将在当前目录打包为 ZIP；源内容上限为 512 MB。',
  archiveExtractHint: '压缩包保留在当前目录，并在旁边新建文件夹解压；可修改文件夹名称。',
  archiveName: '压缩包名称', archiveFolderName: '解压文件夹名称',
  archiveSelectionChanged: '选中的项目已变化，请重新选择后再压缩。',
  archiveUnsupportedSpace: '该文件空间暂不支持压缩与解压。', archiveCrossSpace: '不能跨空间压缩。',
  archiveSameParent: '请选择同一目录中的文件和文件夹。', archiveInvalidName: '请输入压缩包名称。', archiveInvalidFolderName: '请输入解压文件夹名称。',
  archiveCreated: '已创建 {name}', archiveExtracting: '解压中…',
  archiveFailed: '操作失败，请稍后重试。',
  downloadFailed: '下载失败，请稍后重试。',
})
Object.assign(filesUi['ja-JP'], {
  compress: '圧縮', extract: '解凍', archiveCompressTitle: '選択項目を圧縮', archiveExtractTitle: 'ファイルを解凍',
  archiveCompressHint: '選択したファイルとフォルダーを現在のフォルダーで ZIP にまとめます。元データの上限は 512 MB です。',
  archiveExtractHint: 'アーカイブを現在のフォルダーに残し、隣に新しいフォルダーを作成して展開します。フォルダー名は変更できます。',
  archiveName: 'アーカイブ名', archiveFolderName: '展開先フォルダー名',
  archiveSelectionChanged: '選択内容が変更されました。選び直してから圧縮してください。',
  archiveUnsupportedSpace: 'このファイル領域では圧縮・解凍できません。', archiveCrossSpace: '異なる領域をまたいで圧縮することはできません。',
  archiveSameParent: '同じフォルダー内のファイルとフォルダーを選択してください。', archiveInvalidName: 'アーカイブ名を入力してください。', archiveInvalidFolderName: '展開先フォルダー名を入力してください。',
  archiveCreated: '{name} を作成しました', archiveExtracting: '解凍中…',
  archiveFailed: '処理に失敗しました。しばらくしてから再試行してください。',
  downloadFailed: 'ダウンロードに失敗しました。しばらくしてから再試行してください。',
})
Object.assign(filesUi['en-US'], {
  compress: 'Compress', extract: 'Extract', archiveCompressTitle: 'Compress selected items', archiveExtractTitle: 'Extract archive',
  archiveCompressHint: 'Selected files and folders will be packed into a ZIP in the current folder. Source content is limited to 512 MB.',
  archiveExtractHint: 'The archive stays here; its contents are extracted into a new folder beside it. You can edit the folder name.',
  archiveName: 'Archive name', archiveFolderName: 'Extraction folder name',
  archiveSelectionChanged: 'The selection changed. Select the items again before compressing.',
  archiveUnsupportedSpace: 'Compression and extraction are not supported in this file space.', archiveCrossSpace: 'Items from different spaces cannot be compressed together.',
  archiveSameParent: 'Select files and folders from the same directory.', archiveInvalidName: 'Enter an archive name.', archiveInvalidFolderName: 'Enter an extraction folder name.',
  archiveCreated: 'Created {name}', archiveExtracting: 'Extracting…',
  archiveFailed: 'The operation failed. Please try again later.',
  downloadFailed: 'Download failed. Please try again later.',
})
export const filesViewUi = {
  'zh-CN': { name: '名称', type: '类型', deletedAt: '删除时间', remaining: '剩余', size: '大小', sort: '排列', collapse: '收起内容', view: '查看内容', folder: '文件夹', days: '{count} 天', fileCount: '{count} 个文件', restoreFolder: '恢复文件夹及其内容', permanentDeleteFolder: '永久删除文件夹及其内容', emptyFolder: '空文件夹', restore: '恢复', permanentDelete: '永久删除', emptyTrash: '回收站为空', emptyTrashTitle: '清空回收站', emptyTrashMessage: '所有文件将被永久删除，无法恢复。', deleteFileTitle: '移到回收站', deleteFileMessage: '确认将“{name}”移到回收站？', deleteFolderTitle: '移到回收站', deleteFolderMessage: '确认将文件夹“{name}”及其内容移到回收站？', deleteSelectedTitle: '移到回收站', deleteSelectedMessage: '确认将选中的 {count} 项移到回收站？', permanentDeleteFileTitle: '永久删除文件', permanentDeleteFileMessage: '确认永久删除“{name}”？此操作不可恢复。', permanentDeleteFolderTitle: '永久删除文件夹', permanentDeleteFolderMessage: '确认永久删除文件夹“{name}”及其内容？此操作不可恢复。', permanentDeleteSelectedTitle: '永久删除选中项', permanentDeleteSelectedMessage: '确认永久删除选中的 {count} 项？此操作不可恢复。', confirm: '确认', rename: '重命名', downloadZip: '下载为 ZIP', moveToTrash: '移到回收站', download: '下载', items: '{count} 项', storageUsed: '已用 {used}', storageUsedWithLimit: '已用 {used} / {limit}' },
  'ja-JP': { name: '名前', type: '種類', deletedAt: '削除日時', remaining: '残り', size: 'サイズ', sort: '並べ替え', collapse: '内容を閉じる', view: '内容を表示', folder: 'フォルダー', days: '{count} 日', fileCount: '{count} 件', restoreFolder: 'フォルダーと内容を復元', permanentDeleteFolder: 'フォルダーと内容を完全に削除', emptyFolder: '空のフォルダー', restore: '復元', permanentDelete: '完全に削除', emptyTrash: 'ごみ箱は空です', emptyTrashTitle: 'ごみ箱を空にする', emptyTrashMessage: 'すべてのファイルを完全に削除します。元に戻せません。', deleteFileTitle: 'ごみ箱へ移動', deleteFileMessage: '「{name}」をごみ箱へ移動しますか？', deleteFolderTitle: 'ごみ箱へ移動', deleteFolderMessage: 'フォルダー「{name}」と内容をごみ箱へ移動しますか？', deleteSelectedTitle: 'ごみ箱へ移動', deleteSelectedMessage: '選択した {count} 件をごみ箱へ移動しますか？', permanentDeleteFileTitle: 'ファイルを完全に削除', permanentDeleteFileMessage: '「{name}」を完全に削除しますか？元に戻せません。', permanentDeleteFolderTitle: 'フォルダーを完全に削除', permanentDeleteFolderMessage: 'フォルダー「{name}」と内容を完全に削除しますか？元に戻せません。', permanentDeleteSelectedTitle: '選択項目を完全に削除', permanentDeleteSelectedMessage: '選択した {count} 件を完全に削除しますか？元に戻せません。', confirm: '確認', rename: '名前を変更', downloadZip: 'ZIP でダウンロード', moveToTrash: 'ごみ箱へ移動', download: 'ダウンロード', items: '{count} 件', storageUsed: '使用済み {used}', storageUsedWithLimit: '使用済み {used} / {limit}' },
  'en-US': { name: 'Name', type: 'Type', deletedAt: 'Deleted', remaining: 'Remaining', size: 'Size', sort: 'Sort', collapse: 'Collapse contents', view: 'View contents', folder: 'Folder', days: '{count} days', fileCount: '{count} files', restoreFolder: 'Restore folder and contents', permanentDeleteFolder: 'Permanently delete folder and contents', emptyFolder: 'Empty folder', restore: 'Restore', permanentDelete: 'Delete permanently', emptyTrash: 'Trash is empty', emptyTrashTitle: 'Empty trash', emptyTrashMessage: 'All files will be permanently deleted and cannot be recovered.', deleteFileTitle: 'Move to trash', deleteFileMessage: 'Move “{name}” to the trash?', deleteFolderTitle: 'Move to trash', deleteFolderMessage: 'Move folder “{name}” and its contents to the trash?', deleteSelectedTitle: 'Move to trash', deleteSelectedMessage: 'Move the selected {count} items to the trash?', permanentDeleteFileTitle: 'Delete file permanently', permanentDeleteFileMessage: 'Permanently delete “{name}”? This cannot be undone.', permanentDeleteFolderTitle: 'Delete folder permanently', permanentDeleteFolderMessage: 'Permanently delete folder “{name}” and its contents? This cannot be undone.', permanentDeleteSelectedTitle: 'Delete selected items permanently', permanentDeleteSelectedMessage: 'Permanently delete the selected {count} items? This cannot be undone.', confirm: 'Confirm', rename: 'Rename', downloadZip: 'Download as ZIP', moveToTrash: 'Move to trash', download: 'Download', items: '{count} items', storageUsed: '{used} used', storageUsedWithLimit: '{used} used / {limit}' },
} as const

Object.assign(filesViewUi['zh-CN'], { extractTo: '解压' })
Object.assign(filesViewUi['ja-JP'], { extractTo: '解凍' })
Object.assign(filesViewUi['en-US'], { extractTo: 'Extract' })

export const workspaceUi = {
  'zh-CN': { workspaceDirectories: '工作区', workspaceDirectoriesHint: '位于文件库根目录的独立工作空间，默认工作区不可删除。', createWorkspace: '新建工作区', createWorkspaceHint: '工作区会直接创建在文件库根目录，并作为沙盒的独立目录。', workspaceNamePlaceholder: '工作区名称', defaultWorkspace: '默认', workspaceFileUnit: '文件', workspaceFolderUnit: '文件夹', loadingWorkspaces: '正在加载工作区…', noWorkspaces: '暂无工作区', workspaceLoadFailed: '工作区加载失败', workspaceCreateFailed: '工作区创建失败', renameWorkspace: '重命名工作区', workspaceRenameFailed: '工作区重命名失败', workspaceDeleteFailed: '工作区删除失败', deleteWorkspaceTitle: '删除工作区', deleteWorkspaceMessage: '确认删除「{name}」？\n将删除其中 {files} 个文件、{folders} 个文件夹，并解除 {sessions} 个会话和 {tasks} 个定时任务的绑定。', deleteWorkspace: '删除工作区' },
  'ja-JP': { workspaceDirectories: 'Workspace', workspaceDirectoriesHint: 'ファイル庫ルートの独立した作業空間です。既定の Workspace は削除できません。', createWorkspace: 'Workspace を作成', createWorkspaceHint: 'ファイル庫ルートに独立した Workspace を作成します。', workspaceNamePlaceholder: 'Workspace 名', defaultWorkspace: '既定', workspaceFileUnit: 'ファイル', workspaceFolderUnit: 'フォルダー', loadingWorkspaces: 'Workspace を読み込み中…', noWorkspaces: 'Workspace はありません', workspaceLoadFailed: 'Workspace の読み込みに失敗しました', workspaceCreateFailed: 'Workspace の作成に失敗しました', renameWorkspace: 'Workspace 名を変更', workspaceRenameFailed: 'Workspace 名の変更に失敗しました', workspaceDeleteFailed: 'Workspace の削除に失敗しました', deleteWorkspaceTitle: 'Workspace を削除', deleteWorkspaceMessage: '「{name}」を削除しますか？\nファイル {files} 件、フォルダー {folders} 件を削除し、セッション {sessions} 件とタスク {tasks} 件の関連付けを解除します。', deleteWorkspace: 'Workspace を削除' },
  'en-US': { workspaceDirectories: 'Workspace', workspaceDirectoriesHint: 'Independent workspaces at the file-library root. The default Workspace cannot be deleted.', createWorkspace: 'New Workspace', createWorkspaceHint: 'Create an independent Workspace at the file-library root.', workspaceNamePlaceholder: 'Workspace name', defaultWorkspace: 'Default', workspaceFileUnit: 'files', workspaceFolderUnit: 'folders', loadingWorkspaces: 'Loading Workspaces…', noWorkspaces: 'No Workspaces', workspaceLoadFailed: 'Failed to load Workspaces', workspaceCreateFailed: 'Failed to create Workspace', renameWorkspace: 'Rename Workspace', workspaceRenameFailed: 'Failed to rename Workspace', workspaceDeleteFailed: 'Failed to delete Workspace', deleteWorkspaceTitle: 'Delete Workspace', deleteWorkspaceMessage: 'Delete “{name}”?\nThis removes {files} files and {folders} folders, and unbinds {sessions} sessions and {tasks} scheduled tasks.', deleteWorkspace: 'Delete Workspace' },
} as const
