export const memorySettingsUi = {
  'zh-CN': { title: '记忆运行参数', description: '控制记忆提炼、保留和压缩周期；日常运行无需频繁调整。', system: '记忆系统', systemHint: '开启后 Agent 自动从对话中提炼记忆。', toggleSystem: '切换记忆系统', reflectionThreshold: 'Reflection 触发阈值', reflectionHint: '每隔多少条消息触发一次记忆整理。', dailyRetention: 'Daily 记忆保留天数', dailyHint: '超出后压进 memory.md。' },
  'ja-JP': { title: '記憶の実行パラメータ', description: '記憶の抽出、保持、圧縮周期を管理します。通常は頻繁な変更は不要です。', system: '記憶システム', systemHint: '有効にすると Agent が会話から自動的に記憶を抽出します。', toggleSystem: '記憶システムを切り替え', reflectionThreshold: 'Reflection の起動しきい値', reflectionHint: '記憶整理を起動するメッセージ間隔です。', dailyRetention: 'Daily 記憶の保持日数', dailyHint: '超過分は memory.md に圧縮します。' },
  'en-US': { title: 'Memory runtime parameters', description: 'Control memory extraction, retention, and compression cycles; daily changes are usually unnecessary.', system: 'Memory system', systemHint: 'When enabled, Agent automatically extracts memories from conversations.', toggleSystem: 'Toggle memory system', reflectionThreshold: 'Reflection trigger threshold', reflectionHint: 'How many messages trigger one memory cleanup.', dailyRetention: 'Daily memory retention days', dailyHint: 'Older entries are compressed into memory.md.' },
} as const
export const memoryMaintenanceUi = {
  'zh-CN': { title: '记忆维护', description: '批量复核所有用户的记忆，先预览，确认无误后再执行。', preview: '生成预览', previewing: '预览中…', previewHint: '后台只读分析，不会直接写入数据', completedEmpty: '预览完成：没有需要处理的内容', completed: '预览完成：{users} 个用户，共删 {removed} 条 / 搬 {moved} 条去画像 / 迁 {events} 条画像事件到 memory / 迁 {daily} 条 daily / 清 {legacy} 个遗留文件', details: '查看明细', collapseDetails: '收起明细', executing: '执行中…', confirmExecute: '确认执行', imTitle: 'IM 群组与成员记忆', imDescription: '调用维护模型生成只读汇总预览，不展示用户、群组或成员标识。', readOnly: '只读分析，后台运行', scopes: '作用域', groups: '群组', members: '成员', entries: '记忆条目', suggested: '模型建议整理', needsMaintenance: '需整理作用域', failedJobs: '失败任务', maintenanceHint: '只会整理尚未反思的新消息，不会删除已有记忆。', confirmAll: '确认整理全部待处理内容' },
  'ja-JP': { title: '記憶メンテナンス', description: '全ユーザーの記憶を一括確認します。プレビューで確認してから実行します。', preview: 'プレビューを生成', previewing: 'プレビュー中…', previewHint: '読み取り専用の分析で、データは直接変更しません', completedEmpty: 'プレビュー完了：処理対象はありません', completed: 'プレビュー完了：{users} ユーザー、削除 {removed} 件 / プロフィールへ移動 {moved} 件 / memory へ移動 {events} 件 / daily 移行 {daily} 件 / 遺留ファイル削除 {legacy} 件', details: '詳細を表示', collapseDetails: '詳細を閉じる', executing: '実行中…', confirmExecute: '実行を確認', imTitle: 'IM グループとメンバーの記憶', imDescription: 'メンテナンスモデルで読み取り専用の集計プレビューを生成します。識別子は表示しません。', readOnly: '読み取り専用分析、バックグラウンド実行', scopes: 'スコープ', groups: 'グループ', members: 'メンバー', entries: '記憶項目', suggested: 'モデル推奨整理', needsMaintenance: '整理が必要なスコープ', failedJobs: '失敗タスク', maintenanceHint: '未反映の新しいメッセージだけを整理し、既存の記憶は削除しません。', confirmAll: '未処理項目をすべて整理' },
  'en-US': { title: 'Memory maintenance', description: 'Review all users’ memories in bulk. Preview first, then apply after confirmation.', preview: 'Generate preview', previewing: 'Previewing…', previewHint: 'Read-only background analysis; it does not write data directly', completedEmpty: 'Preview complete: nothing needs processing', completed: 'Preview complete: {users} users, removed {removed} / moved to profile {moved} / moved profile events to memory {events} / migrated daily {daily} / removed legacy files {legacy}', details: 'View details', collapseDetails: 'Collapse details', executing: 'Executing…', confirmExecute: 'Confirm execution', imTitle: 'IM group and member memory', imDescription: 'Generate a read-only summary with the maintenance model without showing user, group, or member identifiers.', readOnly: 'Read-only analysis in the background', scopes: 'Scopes', groups: 'Groups', members: 'Members', entries: 'Memory entries', suggested: 'Model suggestions', needsMaintenance: 'Scopes needing maintenance', failedJobs: 'Failed jobs', maintenanceHint: 'Only unreflected new messages are organized; existing memories are not deleted.', confirmAll: 'Organize all pending items' },
} as const
