<template>
  <FileBrowserList @empty-context="openCtx('empty', null, $event)">
    <div class="list-head"><span v-for="item in headers" :key="item.key" class="lh-sortable" :class="{ active: sortKey === item.key }" @click="onSortSelect(item.key)">{{ item.label }}<svg v-if="item.key" class="lh-arrow" :class="{ desc: sortDir === 'desc' }" width="8" height="8" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M5 2v6M2 5l3-3 3 3"/></svg></span></div>
    <div v-for="f in sortedContents.folders" :key="f.id" class="list-row folder-row" :class="{ selected: selectedFolderKeys.has(f.id), 'pre-selected': previewFolderKeys.has(f.id), 'drag-over': dragOverFolderId === f.folderId }" :data-folder-key="f.id" :data-folder-id="f.folderId" @click.stop="handleFolderClick(f, $event)" @contextmenu.prevent.stop="openCtx('folder', f, $event)" @pointerdown="onFolderPointerDown(f, $event)">
      <span class="lr-name-cell"><component :is="folderListIcon(f)" class="lr-folder-icon" :size="16" weight="fill" :style="{ color: folderAccentColor(f) }" /><span class="lr-filename" :title="f.displayName"><span v-if="renamingFolderKey === f.folderId" class="rename-sizer" @click.stop><span class="rename-ghost">{{ renameText || ' ' }}</span><input class="rename-input-inline" v-model="renameText" v-enter="commitRename" @keydown.esc="cancelRename" @blur="commitRename" @focus="($event.target as HTMLInputElement).select()" /></span><template v-else>{{ f.displayName }}</template></span></span>
      <span class="lr-type-text">文件夹</span><span class="lr-text">—</span><span class="lr-text">{{ f.count != null ? f.count + ' 项' : '—' }}</span><span class="lr-text">—</span><span class="lr-actions"><Transition name="sel-cb"><div v-if="inSelectionMode" class="sel-checkbox" :class="{ checked: selectedFolderKeys.has(f.id) }"><svg v-if="selectedFolderKeys.has(f.id)" width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="white" stroke-width="2.2" stroke-linecap="round"><path d="M2 6l3 3 5-5"/></svg></div></Transition><template v-if="f.type === 'folder' && !inSelectionMode"><button class="file-list-btn" @mousedown.prevent @click.stop="renamingFolderKey === f.folderId ? commitRename() : startRenameFolder(f)"><PhCheck v-if="renamingFolderKey === f.folderId" :size="11" /><PhPencilSimple v-else :size="11" /></button><button class="file-list-btn" title="下载为 ZIP" @click.stop="downloadFolder(f)"><PhDownloadSimple :size="11" /></button><button class="file-list-btn del" title="删除" @click.stop="deleteFolder(f)"><PhTrash :size="11" /></button></template></span>
    </div>
    <div v-for="f in sortedContents.files" :key="f.id" class="list-row" :class="{ selected: selectedIds.has(f.id), 'pre-selected': previewFileIds.has(f.id), dragging: draggingFileIds.has(f.id), cut: cbStore.type === 'cut' && cbStore.fileIds.includes(f.id) }" :data-file-id="f.id" @contextmenu.prevent.stop="openCtx('file', f, $event)" @click.stop="handleFileClick(f, $event)" @pointerdown="onFilePointerDown(f, $event)">
      <span class="lr-name-cell"><component :is="fileListIcon(f.ext)" class="lr-file-icon" :size="16" weight="fill" :style="{ color: fileIconColor(f.ext) }" /><span class="lr-filename" :title="f.displayName"><span v-if="renamingFileId === f.id" class="rename-sizer" @click.stop><span class="rename-ghost">{{ renameText || ' ' }}</span><input class="rename-input-inline" v-model="renameText" v-enter="commitRename" @keydown.esc="cancelRename" @blur="commitRename" @focus="($event.target as HTMLInputElement).select()" /></span><template v-else>{{ f.displayName }}</template></span></span>
      <span class="lr-type-cell"><span class="lr-ext" :style="{ color: fileIconColor(f.ext), background: fileIconColor(f.ext) + '18' }">{{ f.ext }}</span></span><span class="lr-proj-cell"><span v-if="f.projectColor" class="lr-dot" :style="{ background: f.projectColor || '' }"></span><span class="lr-projname">{{ f.projectName || f.stageName || '—' }}</span></span><span class="lr-text">{{ f.size }}</span><span class="lr-text">{{ f.createdAt }}</span><span class="lr-actions"><Transition name="sel-cb"><div v-if="inSelectionMode" class="sel-checkbox" :class="{ checked: selectedIds.has(f.id) }"><svg v-if="selectedIds.has(f.id)" width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="white" stroke-width="2.2" stroke-linecap="round"><path d="M2 6l3 3 5-5"/></svg></div></Transition><template v-if="!inSelectionMode"><button class="file-list-btn" @mousedown.prevent @click.stop="renamingFileId === f.id ? commitRename() : startRenameFile(f)"><PhCheck v-if="renamingFileId === f.id" :size="11" /><PhPencilSimple v-else :size="11" /></button><button class="file-list-btn" title="下载" @click.stop="downloadFile(f)"><PhDownloadSimple :size="11" /></button><button class="file-list-btn del" title="移到回收站" @click.stop="deleteSingleFile(f)"><PhTrash :size="11" /></button></template></span>
    </div>
    <FileUploadGhostCard v-for="g in uploadingItems" :key="g.uid" mode="list" :name="g.name" :ext="g.ext" :is-folder="g.isFolder" :progress="g.progress" :done="g.done" :total="g.total" :failed="g.failed" :error="g.error"><template #list="{ color, statusText }"><span class="lr-name-cell"><PhFolder v-if="g.isFolder" class="lr-file-icon" :size="16" weight="fill" :style="{ color }" /><component v-else :is="fileListIcon(g.ext)" class="lr-file-icon" :size="16" weight="fill" :style="{ color }" /><span class="lr-filename">{{ g.name }}</span></span><span class="lr-type-cell"><span v-if="!g.isFolder" class="lr-ext" :style="{ color: fileIconColor(g.ext), background: fileIconColor(g.ext) + '18' }">{{ g.ext || '—' }}</span></span><span class="lr-text">—</span><span class="lr-text">—</span><span class="lr-text">{{ statusText }}</span><span class="lr-actions" /></template></FileUploadGhostCard>
    <FileBrowserEmptyState v-if="contents.folders.length === 0 && contents.files.length === 0 && !loading" variant="list" />
    <FileUploadButton v-if="canUpload" mode="list" @select="handleFileInput" />
  </FileBrowserList>
</template>
<script setup lang="ts">
import type { PropType } from 'vue'
import { PhCheck, PhDownloadSimple, PhFolder, PhPencilSimple, PhTrash } from '@phosphor-icons/vue'
import FileBrowserList from '@/components/common/file-browser/FileBrowserList.vue'
import FileBrowserEmptyState from '@/components/common/file-browser/FileBrowserEmptyState.vue'
import FileUploadButton from '@/components/common/file-browser/FileUploadButton.vue'
import FileUploadGhostCard from '@/components/common/file-browser/FileUploadGhostCard.vue'
const props = defineProps({ context: { type: Object as PropType<Record<string, any>>, required: true } })
const headers = [{ key: 'name', label: '名称' }, { key: 'type', label: '类型' }, { key: 'stage', label: '项目 / 阶段' }, { key: 'size', label: '大小' }, { key: 'createdAt', label: '日期' }, { key: '', label: '' }]
const { contents, sortedContents, sortKey, sortDir, onSortSelect, openCtx, selectedFolderKeys, previewFolderKeys, dragOverFolderId, handleFolderClick, onFolderPointerDown, folderListIcon, folderAccentColor, renamingFolderKey, renameText, commitRename, cancelRename, startRenameFolder, downloadFolder, deleteFolder, inSelectionMode, selectedIds, previewFileIds, draggingFileIds, cbStore, handleFileClick, onFilePointerDown, fileListIcon, fileIconColor, renamingFileId, startRenameFile, downloadFile, deleteSingleFile, uploadingItems, loading, canUpload, handleFileInput } = props.context
</script>
