import {
  RiAddLine,
  RiAlarmLine,
  RiAppsLine,
  RiArchiveLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowDownLine,
  RiArrowDownDoubleLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiBardLine,
  RiCalendar2Line,
  RiCalendarEventLine,
  RiCalendarLine,
  RiCameraLine,
  RiChat1Line,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCheckboxLine,
  RiCloseLine,
  RiComputerLine,
  RiDeleteBinLine,
  RiDeleteBin6Line,
  RiDownloadLine,
  RiExpandDiagonalLine,
  RiCollapseDiagonalLine,
  RiEditLine,
  RiErrorWarningLine,
  RiAlarmWarningLine,
  RiBrainLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFileLine,
  RiFolderAddLine,
  RiFolder3Line,
  RiFolder5Line,
  RiFolderLine,
  RiFolderOpenLine,
  RiFoldersLine,
  RiBarChartLine,
  RiBugLine,
  RiBookletLine,
  RiClipboardLine,
  RiCupLine,
  RiEqualizerLine,
  RiFlagLine,
  RiFunctionLine,
  RiLineChartLine,
  RiSpeedLine,
  RiTerminalLine,
  RiGroupLine,
  RiImageLine,
  RiInformationLine,
  RiLayoutGridLine,
  RiListUnordered,
  RiLoaderLine,
  RiLogoutBoxLine,
  RiLightbulbLine,
  RiMailLine,
  RiMailSendLine,
  RiMicLine,
  RiMoreLine,
  RiNotification3Line,
  RiPauseLine,
  RiPlayLine,
  RiPlayFill,
  RiPushpinFill,
  RiPushpinLine,
  RiPuzzleLine,
  RiPulseLine,
  RiQuestionLine,
  RiRefreshLine,
  RiRobotLine,
  RiRobot2Line,
  RiSearchLine,
  RiScissorsLine,
  RiSettings3Line,
  RiShieldCheckFill,
  RiShieldCheckLine,
  RiSidebarUnfoldLine,
  RiSortAsc,
  RiStackLine,
  RiStopLine,
  RiStopFill,
  RiSubtractLine,
  RiSunLine,
  RiMoonLine,
  RiTeamLine,
  RiTrelloLine,
  RiTimeLine,
  RiUploadLine,
  RiVideoLine,
  RiUserLine,
  RiUser3Line,
  RiUserUnfollowLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiWrenchLine,
} from '@remixicon/vue'
import type { IconComponent } from './iconTypes'

/** 业务语义到 Remix Icon 的唯一映射入口。 */
export const iconRegistry = {
  'action.add': RiAddLine,
  'action.archive': RiArchiveLine,
  'action.back': RiArrowLeftLine,
  'action.chevron-back': RiArrowLeftSLine,
  'action.down': RiArrowDownLine,
  'action.scroll-down': RiArrowDownDoubleLine,
  'action.close': RiCloseLine,
  'action.list': RiListUnordered,
  'action.copy': RiFileCopyLine,
  'action.cut': RiScissorsLine,
  'action.delete': RiDeleteBinLine,
  'action.clear': RiDeleteBin6Line,
  'action.download': RiDownloadLine,
  'action.edit': RiEditLine,
  'action.more': RiMoreLine,
  'action.next': RiArrowRightLine,
  'action.chevron-next': RiArrowRightSLine,
  'action.pause': RiPauseLine,
  'action.play': RiPlayLine,
  'action.search': RiSearchLine,
  'action.send': RiMailSendLine,
  'action.sort': RiSortAsc,
  'action.stop': RiStopLine,
  'action.stop-fill': RiStopFill,
  'action.subtract': RiSubtractLine,
  'action.upload': RiUploadLine,
  'action.refresh': RiRefreshLine,
  'action.expand': RiExpandDiagonalLine,
  'action.collapse': RiCollapseDiagonalLine,
  'admin.alarm': RiAlarmLine,
  'admin.alarm-warning': RiAlarmWarningLine,
  'admin.analytics': RiLineChartLine,
  'admin.bar-chart': RiBarChartLine,
  'admin.bug': RiBugLine,
  'admin.brain': RiBrainLine,
  'admin.clipboard': RiClipboardLine,
  'admin.bell': RiNotification3Line,
  'admin.computer': RiComputerLine,
  'admin.question': RiQuestionLine,
  'admin.eye': RiEyeLine,
  'admin.folder': RiFolderLine,
  'admin.folders': RiFoldersLine,
  'admin.flag': RiFlagLine,
  'admin.gauge': RiSpeedLine,
  'admin.lightbulb': RiLightbulbLine,
  'admin.mail': RiMailLine,
  'admin.microphone': RiMicLine,
  'admin.pulse': RiPulseLine,
  'admin.robot': RiRobotLine,
  'admin.robot2': RiRobot2Line,
  'admin.sliders': RiEqualizerLine,
  'admin.stack': RiStackLine,
  'admin.terminal': RiTerminalLine,
  'admin.video': RiVideoLine,
  'admin.settings': RiSettings3Line,
  'admin.shield': RiShieldCheckLine,
  'admin.shieldAuthorized': RiShieldCheckFill,
  'admin.time': RiTimeLine,
  'admin.wrench': RiWrenchLine,
  'canvas.graph': RiAppsLine,
  'canvas.note': RiBookletLine,
  'canvas.pin': RiPushpinFill,
  'canvas.pin-off': RiPushpinLine,
  'communication.chat': RiChat1Line,
  'communication.customer': RiUser3Line,
  'communication.group': RiGroupLine,
  'communication.microphone': RiMicLine,
  'communication.team': RiTeamLine,
  'file.document': RiFileLine,
  'file.function': RiFunctionLine,
  'file.folder': RiFolder5Line,
  'file.folder-add': RiFolderAddLine,
  'file.folder-open': RiFolderOpenLine,
  'project.month-folder': RiFolder3Line,
  'file.image': RiImageLine,
  'resource.skill': RiPuzzleLine,
  'media.pause': RiPauseLine,
  'media.play': RiPlayLine,
  'media.play-fill': RiPlayFill,
  'media.speaker-high': RiVolumeUpLine,
  'media.speaker-low': RiVolumeDownLine,
  'media.speaker-off': RiVolumeMuteLine,
  'navigation.apps': RiAppsLine,
  'navigation.projects': RiTrelloLine,
  'navigation.calendar': RiCalendarEventLine,
  'navigation.calendar-add': RiCalendar2Line,
  'navigation.grid': RiLayoutGridLine,
  'navigation.list': RiListUnordered,
  'navigation.sidebar': RiSidebarUnfoldLine,
  'status.check-circle': RiCheckboxCircleLine,
  'status.check-square': RiCheckboxLine,
  'status.info': RiInformationLine,
  'status.loading': RiLoaderLine,
  'status.success': RiCheckLine,
  'status.warning': RiErrorWarningLine,
  'status.warning-octagon': RiErrorWarningLine,
  'user.camera': RiCameraLine,
  'user.default': RiUserLine,
  'user.gugu': RiCupLine,
  'user.remove': RiUserUnfollowLine,
  'user.security': RiShieldCheckLine,
  'user.settings': RiSettings3Line,
  'user.sign-out': RiLogoutBoxLine,
  'theme.dark': RiMoonLine,
  'theme.light': RiSunLine,
  'theme.system': RiComputerLine,
} satisfies Record<string, IconComponent>

export type IconName = keyof typeof iconRegistry

export function resolveIcon(name: string): IconComponent {
  const icon = iconRegistry[name as IconName]
  if (icon) return icon
  throw new Error(`[Icon] 未注册图标语义：${name}`)
}
