import {
  RiAddLine,
  RiAlarmLine,
  RiAppsLine,
  RiArchiveLine,
  RiArrowLeftLine,
  RiArrowDownLine,
  RiArrowRightLine,
  RiBardLine,
  RiCalendar2Line,
  RiCalendarLine,
  RiCameraLine,
  RiChat1Line,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCheckboxLine,
  RiCloseLine,
  RiComputerLine,
  RiDeleteBinLine,
  RiDownloadLine,
  RiExpandDiagonalLine,
  RiCollapseDiagonalLine,
  RiEditLine,
  RiErrorWarningLine,
  RiFileCopyLine,
  RiFileLine,
  RiFolderAddLine,
  RiFolderLine,
  RiFolderOpenLine,
  RiGroupLine,
  RiImageLine,
  RiInformationLine,
  RiLayoutGridLine,
  RiListUnordered,
  RiLoaderLine,
  RiLogoutBoxLine,
  RiMailSendLine,
  RiMicLine,
  RiMoreLine,
  RiMindMap,
  RiNotification3Line,
  RiPauseLine,
  RiPlayLine,
  RiPushpinLine,
  RiQuestionLine,
  RiSearchLine,
  RiScissorsLine,
  RiSettings3Line,
  RiShieldCheckLine,
  RiSidebarUnfoldLine,
  RiSortAsc,
  RiStackLine,
  RiStopLine,
  RiSubtractLine,
  RiSunLine,
  RiMoonLine,
  RiTeamLine,
  RiTimeLine,
  RiUploadLine,
  RiUserLine,
  RiUser3Line,
  RiUserUnfollowLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiWrenchLine,
} from '@remixicon/vue'
import type { IconComponent } from './iconTypes'

/** 业务语义到 Remix Icon 的唯一映射入口。 */
export const iconRegistry = {
  'action.add': RiAddLine,
  'action.archive': RiArchiveLine,
  'action.back': RiArrowLeftLine,
  'action.down': RiArrowDownLine,
  'action.close': RiCloseLine,
  'action.copy': RiFileCopyLine,
  'action.cut': RiScissorsLine,
  'action.delete': RiDeleteBinLine,
  'action.download': RiDownloadLine,
  'action.edit': RiEditLine,
  'action.more': RiMoreLine,
  'action.next': RiArrowRightLine,
  'action.pause': RiPauseLine,
  'action.play': RiPlayLine,
  'action.search': RiSearchLine,
  'action.send': RiMailSendLine,
  'action.sort': RiSortAsc,
  'action.stop': RiStopLine,
  'action.subtract': RiSubtractLine,
  'action.upload': RiUploadLine,
  'action.expand': RiExpandDiagonalLine,
  'action.collapse': RiCollapseDiagonalLine,
  'admin.alarm': RiAlarmLine,
  'admin.bell': RiNotification3Line,
  'admin.computer': RiComputerLine,
  'admin.question': RiQuestionLine,
  'admin.settings': RiSettings3Line,
  'admin.time': RiTimeLine,
  'admin.wrench': RiWrenchLine,
  'canvas.graph': RiAppsLine,
  'canvas.note': RiMindMap,
  'canvas.pin': RiPushpinLine,
  'canvas.pin-off': RiPushpinLine,
  'communication.chat': RiChat1Line,
  'communication.customer': RiUser3Line,
  'communication.group': RiGroupLine,
  'communication.microphone': RiMicLine,
  'communication.team': RiTeamLine,
  'file.document': RiFileLine,
  'file.folder': RiFolderLine,
  'file.folder-add': RiFolderAddLine,
  'file.folder-open': RiFolderOpenLine,
  'file.image': RiImageLine,
  'media.pause': RiPauseLine,
  'media.play': RiPlayLine,
  'media.speaker-high': RiVolumeUpLine,
  'media.speaker-low': RiVolumeDownLine,
  'media.speaker-off': RiVolumeMuteLine,
  'navigation.apps': RiAppsLine,
  'navigation.projects': RiStackLine,
  'navigation.calendar': RiCalendarLine,
  'navigation.calendar-add': RiCalendar2Line,
  'navigation.grid': RiLayoutGridLine,
  'navigation.list': RiListUnordered,
  'navigation.sidebar': RiSidebarUnfoldLine,
  'status.check-circle': RiCheckboxCircleLine,
  'status.check-square': RiCheckboxLine,
  'status.info': RiInformationLine,
  'status.loading': RiLoaderLine,
  'status.success': RiCheckLine,
  'status.warning': RiErrorWarningLine,
  'status.warning-octagon': RiErrorWarningLine,
  'user.camera': RiCameraLine,
  'user.default': RiUserLine,
  'user.gugu': RiBardLine,
  'user.remove': RiUserUnfollowLine,
  'user.security': RiShieldCheckLine,
  'user.settings': RiSettings3Line,
  'user.sign-out': RiLogoutBoxLine,
  'theme.dark': RiMoonLine,
  'theme.light': RiSunLine,
  'theme.system': RiComputerLine,
} satisfies Record<string, IconComponent>

export type IconName = keyof typeof iconRegistry

export function resolveIcon(name: string): IconComponent {
  const icon = iconRegistry[name as IconName]
  if (icon) return icon
  throw new Error(`[Icon] 未注册图标语义：${name}`)
}
