<template>
  <div v-if="usageLoading && !usage" class="usage-loading">加载中…</div>
  <template v-else-if="usage">
    <div class="usage-summary"><div v-for="item in summary" :key="item.label" class="usage-stat-card"><div class="usc-label">{{ item.label }}</div><div class="usc-num">{{ item.value }}</div><div class="usc-sub">总计 {{ item.total }}</div></div></div>
    <div class="config-card chart-card"><div class="chart-header"><div class="metric-tabs"><button v-for="metric in metrics" :key="metric.key" class="metric-tab" :class="{ active: activeMetric === metric.key }" @click="activeMetric = metric.key">{{ metric.label }}</button><span v-if="activeModel" class="model-filter-tag">{{ activeModel }}</span></div><div class="month-nav"><button class="month-arrow" :disabled="monthIndex >= usage.months.length - 1" @click="switchMonth(1)">‹</button><span class="month-label">{{ usage.month }}</span><button class="month-arrow" :disabled="monthIndex <= 0" @click="switchMonth(-1)">›</button></div></div><AdminLineChart :labels="usage.daily.map((d: any) => d.date.slice(8))" :values="usage.daily.map((d: any) => Number(d[activeMetric] || 0))" :unit="metrics.find(m => m.key === activeMetric)?.unit || ''" /></div>
    <div v-if="usage.by_model.length" class="config-card"><div class="card-head"><div class="card-title-block"><h3>按模型</h3><p>点击行在图表中单独查看；缓存数据来自模型返回的 usage</p></div><button v-if="activeModel" class="clear-model-btn" @click="toggleModel(activeModel)">清除筛选</button></div><div class="model-table"><div class="mt-row mt-head"><span>模型</span><span>对话数</span><span>输入</span><span>输出</span><span>命中缓存</span></div><div v-for="model in usage.by_model" :key="model.model" class="mt-row mt-clickable" :class="{ 'mt-active': activeModel === model.model, 'mt-dimmed': activeModel && activeModel !== model.model }" @click="toggleModel(model.model)"><span class="mt-model">{{ model.model }}<em>{{ model.provider }}</em></span><span>{{ model.calls }}</span><span>{{ fmtNum(model.tokens_in) }}</span><span>{{ fmtNum(model.tokens_out) }}</span><span>{{ fmtNum(model.cache_read) }}</span></div></div></div>
    <div v-if="!usage.by_model.length && !usage.daily.some((day: any) => day.calls > 0)" class="usage-empty">暂无数据，发起对话后将开始记录</div>
  </template>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { useUsage } from '../useUsage'
import AdminLineChart from '@/components/admin/AdminLineChart.vue'
const { usage, usageLoading, activeModel, activeMetric, metrics, monthIndex, toggleModel, switchMonth, fmtNum } = useUsage()
const summary = computed(() => usage.value ? [{ label: '今日对话', value: usage.value.today.calls, total: usage.value.total.calls }, { label: '今日输入 tokens', value: fmtNum(usage.value.today.tokens_in), total: fmtNum(usage.value.total.tokens_in) }, { label: '今日输出 tokens', value: fmtNum(usage.value.today.tokens_out), total: fmtNum(usage.value.total.tokens_out) }, { label: '命中缓存 tokens', value: fmtNum(usage.value.today.cache_read), total: fmtNum(usage.value.total.cache_read) }, { label: '缓存命中率', value: `${((usage.value.today.cache_ratio || 0) * 100).toFixed(1)}%`, total: `${((usage.value.total.cache_ratio || 0) * 100).toFixed(1)}%` }] : [])
</script>
<style scoped>
.usage-loading,.usage-empty{text-align:center;padding:64px 0;font-size:13px;color:rgba(255,255,255,.2)}.usage-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:12px}.usage-stat-card,.config-card{background:rgba(255,255,255,.05);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:20px 22px;box-shadow:0 4px 24px rgba(0,0,0,.25)}.usc-label{font-size:11px;color:rgba(255,255,255,.3);font-weight:600;margin-bottom:10px}.usc-num{font-size:28px;font-weight:700;color:rgba(255,255,255,.88);line-height:1}.usc-sub{font-size:12px;color:rgba(255,255,255,.25);margin-top:6px}.chart-card{margin-bottom:12px}.chart-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.metric-tabs{display:flex;gap:4px}.metric-tab,.month-arrow,.clear-model-btn{padding:5px 14px;border-radius:8px;border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.04);color:rgba(255,255,255,.5);cursor:pointer}.metric-tab.active{background:rgba(123,127,178,.2);color:rgba(255,255,255,.88)}.month-nav{display:flex;align-items:center;gap:8px}.month-label{font-size:13px;min-width:64px;text-align:center}.month-arrow{width:28px;padding:5px}.chart-wrap{position:relative;width:100%}.line-chart{display:block;overflow:visible}.chart-tooltip{position:absolute;pointer-events:none;background:rgba(16,16,26,.95);border:1px solid rgba(149,144,196,.25);border-radius:10px;padding:9px 14px;transform:translate(-50%,-115%);white-space:nowrap}.tt-date{font-size:11px;color:rgba(255,255,255,.35);margin-bottom:4px}.tt-val{font-size:18px;font-weight:700;color:rgba(255,255,255,.92)}.tt-val span{font-size:11px;font-weight:400;color:rgba(255,255,255,.35)}.card-head{display:flex;align-items:center;gap:13px;margin-bottom:20px}.card-title-block{flex:1}.card-title-block h3{font-size:14px}.card-title-block p{font-size:12px;color:rgba(255,255,255,.38);margin-top:2px}.model-table{display:flex;flex-direction:column}.mt-row{display:grid;grid-template-columns:1fr 80px 90px 90px;padding:10px 4px;font-size:13px;border-bottom:1px solid rgba(255,255,255,.05);align-items:center}.mt-head{font-size:11px;color:rgba(255,255,255,.25)}.mt-clickable{cursor:pointer}.mt-clickable:hover{background:rgba(255,255,255,.04)}.mt-active{background:rgba(123,127,178,.12)}.mt-dimmed{opacity:.35}.mt-model{color:rgba(255,255,255,.8)}.mt-model em{display:block;font-style:normal;font-size:11px;color:rgba(255,255,255,.28);margin-top:2px}.mt-row span:not(:first-child){text-align:right;color:rgba(255,255,255,.55)}.model-filter-tag{display:inline-flex;padding:3px 10px;border-radius:6px;background:rgba(123,127,178,.18);font-size:12px;color:rgba(169,164,216,.9)}@media(max-width:720px){.usage-summary{grid-template-columns:1fr}.mt-row{grid-template-columns:1fr 55px 65px 65px}}
</style>
