<template>
    <div v-if="usageLoading && !usage" class="usage-loading">{{ t('adminUsageUi.loading') }}</div>
  <template v-else-if="usage">
    <div class="period-tabs"><button class="period-tab" :class="{ active: period === 'today' }" @click="period = 'today'">{{ t('adminUsageUi.today') }}</button><button class="period-tab" :class="{ active: period === 'recent' }" @click="period = 'recent'">{{ t('adminUsageUi.recent') }}</button></div>
    <p class="usage-note">{{ usage.usage_basis }} · {{ t('adminUsageUi.timezone') }}: {{ usage.timezone }}</p>
    <div class="usage-summary"><div v-for="item in summary" :key="item.label" class="usage-stat-card"><div class="usc-label">{{ item.label }}</div><div class="usc-num">{{ item.value }}</div><div class="usc-sub">{{ t('adminUsageUi.total') }} {{ item.total }}</div></div></div>
    <div class="config-card chart-card"><div class="chart-header"><div class="metric-tabs"><button v-for="metric in metrics" :key="metric.key" class="metric-tab" :class="{ active: activeMetric === metric.key }" @click="activeMetric = metric.key">{{ metric.label }}</button><span v-if="activeModel" class="model-filter-tag">{{ activeModel }}</span></div><div class="month-nav"><button class="month-arrow" :disabled="monthIndex >= usage.months.length - 1" @click="switchMonth(1)">‹</button><span class="month-label">{{ usage.month }}</span><button class="month-arrow" :disabled="monthIndex <= 0" @click="switchMonth(-1)">›</button></div></div><AdminLineChart :labels="chartData.map((d: any) => d.date.slice(8))" :values="chartValues" :unit="metrics.find(m => m.key === activeMetric)?.unit || ''" /></div>
    <div v-if="usage.by_model.length" class="config-card"><div class="card-head"><div class="card-title-block"><h3>{{ t('adminUsageUi.model') }}</h3><p>{{ t('adminUsageUi.modelHint') }}</p></div><button v-if="activeModel" class="clear-model-btn" @click="toggleModel(activeModel)">{{ t('adminUsageUi.clearFilter') }}</button></div><div class="model-table"><div class="mt-row mt-head"><span>{{ t('adminUsageUi.modelName') }}</span><span>{{ t('adminUsageUi.calls') }}</span><span>{{ t('adminUsageUi.input') }}</span><span>{{ t('adminUsageUi.output') }}</span><span>{{ t('adminUsageUi.cacheRead') }}</span></div><div v-for="model in usage.by_model" :key="model.model" class="mt-row mt-clickable" :class="{ 'mt-active': activeModel === model.model, 'mt-dimmed': activeModel && activeModel !== model.model }" @click="toggleModel(model.model)"><span class="mt-model">{{ model.model }}<em>{{ model.provider }}</em></span><span>{{ model.calls }}</span><span>{{ fmtNum(model.tokens_in) }}</span><span>{{ fmtNum(model.tokens_out) }}</span><span>{{ fmtNum(model.cache_read) }}</span></div></div></div>
    <div v-if="!usage.by_model.length && !chartData.some((day: any) => day.calls > 0)" class="usage-empty">{{ t('adminUsageUi.noData') }}</div>
  </template>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useUsage } from '../useUsage'
import AdminLineChart from '@/components/admin/AdminLineChart.vue'
const { usage, usageLoading, activeModel, activeMetric, metrics, monthIndex, toggleModel, switchMonth, fmtNum } = useUsage()
const { t } = useI18n()
const period = ref<'today' | 'recent'>('today')
const chartData = computed(() => period.value === 'recent' ? (usage.value?.recent_daily || []) : (usage.value?.daily || []))
const chartValues = computed(() => chartData.value.map((day: any) => activeMetric.value === 'cache_ratio' ? Number(day.cache_ratio || 0) * 100 : Number(day[activeMetric.value] || 0)))
const summary = computed(() => {
  if (!usage.value) return []
  const source = period.value === 'today' ? usage.value.today : (usage.value.recent_daily || []).reduce((total: any, day: any) => ({
    calls: total.calls + Number(day.calls || 0),
    tokens_in: total.tokens_in + Number(day.tokens_in || 0),
    tokens_out: total.tokens_out + Number(day.tokens_out || 0),
    cache_read: total.cache_read + Number(day.cache_read || 0),
    cache_write: total.cache_write + Number(day.cache_write || 0),
  }), { calls: 0, tokens_in: 0, tokens_out: 0, cache_read: 0, cache_write: 0 })
  const ratio = source.tokens_in ? source.cache_read / source.tokens_in : 0
  return [{ label: `${period.value === 'today' ? t('adminUsageUi.today') : t('adminUsageUi.recent')}${t('adminUsageUi.calls')}`, value: source.calls, total: usage.value.total.calls }, { label: t('adminUsageUi.input'), value: fmtNum(source.tokens_in), total: fmtNum(usage.value.total.tokens_in) }, { label: t('adminUsageUi.output'), value: fmtNum(source.tokens_out), total: fmtNum(usage.value.total.tokens_out) }, { label: t('adminUsageUi.cacheRead'), value: fmtNum(source.cache_read), total: fmtNum(usage.value.total.cache_read) }, { label: t('adminUsageUi.cacheRate'), value: `${(ratio * 100).toFixed(1)}%`, total: `${((usage.value.total.cache_ratio || 0) * 100).toFixed(1)}%` }]
})
</script>
<style scoped>
.usage-loading,.usage-empty{text-align:center;padding:64px 0;font-size:13px;color:rgba(255,255,255,.2)}.usage-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:12px}.usage-stat-card,.config-card{background:rgba(255,255,255,.05);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:20px 22px;box-shadow:0 4px 24px rgba(0,0,0,.25)}.usc-label{font-size:11px;color:rgba(255,255,255,.3);font-weight:600;margin-bottom:10px}.usc-num{font-size:28px;font-weight:700;color:rgba(255,255,255,.88);line-height:1}.usc-sub{font-size:12px;color:rgba(255,255,255,.25);margin-top:6px}.chart-card{margin-bottom:12px}.chart-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.metric-tabs{display:flex;gap:4px}.metric-tab,.month-arrow,.clear-model-btn{padding:5px 14px;border-radius:8px;border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.04);color:rgba(255,255,255,.5);cursor:pointer}.metric-tab.active{background:rgba(123,127,178,.2);color:rgba(255,255,255,.88)}.month-nav{display:flex;align-items:center;gap:8px}.month-label{font-size:13px;min-width:64px;text-align:center}.month-arrow{width:28px;padding:5px}.chart-wrap{position:relative;width:100%}.line-chart{display:block;overflow:visible}.chart-tooltip{position:absolute;pointer-events:none;background:rgba(16,16,26,.95);border:1px solid rgba(149,144,196,.25);border-radius:10px;padding:9px 14px;transform:translate(-50%,-115%);white-space:nowrap}.tt-date{font-size:11px;color:rgba(255,255,255,.35);margin-bottom:4px}.tt-val{font-size:18px;font-weight:700;color:rgba(255,255,255,.92)}.tt-val span{font-size:11px;font-weight:400;color:rgba(255,255,255,.35)}.card-head{display:flex;align-items:center;gap:13px;margin-bottom:20px}.card-title-block{flex:1}.card-title-block h3{font-size:14px}.card-title-block p{font-size:12px;color:rgba(255,255,255,.38);margin-top:2px}.model-table{display:flex;flex-direction:column;overflow-x:auto}.mt-row{display:grid;grid-template-columns:minmax(160px,1fr) repeat(4,minmax(64px,90px));min-width:520px;padding:10px 4px;font-size:13px;border-bottom:1px solid rgba(255,255,255,.05);align-items:center}.mt-head{font-size:11px;color:rgba(255,255,255,.25)}.mt-clickable{cursor:pointer}.mt-clickable:hover{background:rgba(255,255,255,.04)}.mt-active{background:rgba(123,127,178,.12)}.mt-dimmed{opacity:.35}.mt-model{color:rgba(255,255,255,.8)}.mt-model em{display:block;font-style:normal;font-size:11px;color:rgba(255,255,255,.28);margin-top:2px}.mt-row span:not(:first-child){text-align:right;color:rgba(255,255,255,.55)}.model-filter-tag{display:inline-flex;padding:3px 10px;border-radius:6px;background:rgba(123,127,178,.18);font-size:12px;color:rgba(169,164,216,.9)}@media(max-width:720px){.usage-summary{grid-template-columns:1fr}.mt-row{grid-template-columns:minmax(140px,1fr) repeat(4,65px)}}
.period-tabs{display:inline-flex;gap:4px;margin-bottom:12px;padding:3px;border:1px solid rgba(255,255,255,.09);border-radius:10px;background:rgba(255,255,255,.04);width:max-content;max-width:100%;align-self:flex-start}.period-tab{border:0;border-radius:7px;padding:5px 13px;background:transparent;color:rgba(255,255,255,.45);font-size:12px;cursor:pointer}.period-tab.active{background:rgba(123,127,178,.2);color:rgba(255,255,255,.9)}
.usage-note{margin:0 0 12px;color:rgba(255,255,255,.34);font-size:11px;line-height:1.5}
</style>
