<template>
  <section class="config-card labels-card"><div class="card-head"><h3>状态命名</h3><p>自定义对话里「状态指示」的显示名。留空＝用默认值。改完保存即时生效。</p></div><div class="labels-tip">💡 <span>一个状态可填<b>多个名称</b>，用竖线 <code>|</code> 分隔，每次显示随机取一个。</span></div><div v-if="labelsLoading" class="placeholder-panel">加载中…</div><template v-else><div class="labels-group-title">特殊状态</div><div class="labels-list"><div v-for="row in stateLabels.special" :key="row.key" class="label-row"><div class="label-meta"><span class="label-key">{{ row.key }}</span><span class="label-default">默认：{{ row.default || '（空）' }}</span></div><div class="label-input-wrap"><input v-model="row.custom" :placeholder="row.default || '留空＝默认'" class="label-input"><button v-if="row.custom" class="label-reset" title="恢复默认" @click="reset(row)">×</button></div></div></div><div class="labels-group-title">工具（{{ filteredTools.length }}/{{ stateLabels.tools.length }}）<input v-model="labelsFilter" placeholder="筛选工具名 / 文案…" class="labels-filter"></div><div class="labels-list"><div v-for="row in filteredTools" :key="row.key" class="label-row"><div class="label-meta"><span class="label-key">{{ row.key }}</span><span class="label-default">默认：{{ row.default }}</span></div><div class="label-input-wrap"><input v-model="row.custom" :placeholder="row.default" class="label-input"><button v-if="row.custom" class="label-reset" title="恢复默认" @click="reset(row)">×</button></div></div></div><div class="labels-save-bar"><span v-if="labelsSaved" class="labels-saved-tip">已保存 ✓</span><button class="btn-primary" :disabled="labelsSaving" @click="save">{{ labelsSaving ? '保存中…' : '保存' }}</button></div></template></section>
</template>
<script setup lang="ts">
import { onMounted } from 'vue'
import { useStateLabels } from '../useStateLabels'
const { stateLabels, labelsLoading, labelsSaving, labelsFilter, labelsSaved, filteredTools, refresh, save, reset } = useStateLabels()
onMounted(refresh)
</script>
<style scoped>
.config-card{background:rgba(255,255,255,.05);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:22px 24px;color:rgba(255,255,255,.82)}.card-head{display:flex;align-items:center;gap:13px;margin-bottom:20px}.card-head h3{font-size:14px}.card-head p{font-size:12px;color:rgba(255,255,255,.38);margin-top:2px}.labels-tip{display:flex;gap:8px;margin-bottom:16px;padding:10px 13px;background:rgba(120,170,255,.09);border:1px solid rgba(120,170,255,.22);border-radius:10px;font-size:12.5px;line-height:1.6}.labels-tip code{font-family:monospace;background:rgba(0,0,0,.3);border-radius:5px;padding:1px 6px;color:#ffd9a8}.labels-group-title{display:flex;align-items:center;gap:10px;margin:18px 2px 8px;font-size:12px;color:rgba(255,255,255,.42)}.labels-filter{margin-left:auto;width:180px;background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.1);border-radius:7px;padding:5px 9px;color:#e6e7f0;font-size:12px}.labels-list{display:grid;grid-template-columns:1fr 1fr;gap:8px 14px}.label-row{display:flex;align-items:center;gap:10px;padding:8px 10px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.06);border-radius:9px}.label-meta{display:flex;flex-direction:column;gap:1px;min-width:0;flex:0 0 40%}.label-key{font-size:12px;color:#cdd0e4;font-family:monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label-default{font-size:10.5px;color:rgba(255,255,255,.3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label-input-wrap{position:relative;flex:1;min-width:0}.label-input{width:100%;box-sizing:border-box;background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.1);border-radius:7px;padding:6px 26px 6px 9px;color:#e6e7f0;font-size:12.5px}.label-reset{position:absolute;right:4px;top:50%;transform:translateY(-50%);width:18px;height:18px;border:0;background:rgba(255,255,255,.08);color:rgba(255,255,255,.55);border-radius:50%;cursor:pointer}.labels-save-bar{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:18px;padding-top:14px;border-top:1px solid rgba(255,255,255,.07)}.labels-saved-tip{font-size:12.5px;color:#7fd6a0}.btn-primary{padding:6px 16px;border:0;border-radius:9px;background:linear-gradient(135deg,#7b7fb2,#9590c4);color:#fff;font-size:13px;font-weight:600}.btn-primary:disabled{opacity:.5}.placeholder-panel{padding:12px;color:rgba(255,255,255,.45)}@media(max-width:720px){.labels-list{grid-template-columns:1fr}}
</style>
<style scoped>
.btn-primary { background: var(--action-primary-bg); color: var(--content-on-accent); cursor: pointer; transition: background-color .15s; }
.btn-primary:hover:not(:disabled) { background: var(--action-primary-bg-hover); }
</style>
