<template>
  <section class="config-card labels-card"><div class="card-head"><h3>{{ t('adminAgentLabels.title') }}</h3><p>{{ t('adminAgentLabels.description') }}</p></div><div class="labels-tip">💡 <span>{{ t('adminAgentLabels.tip') }}</span></div><div v-if="labelsLoading" class="placeholder-panel">{{ t('adminAgentLabels.loading') }}</div><template v-else><div class="labels-group-title">{{ t('adminAgentLabels.special') }}</div><div class="labels-list"><div v-for="row in stateLabels.special" :key="row.key" class="label-row"><div class="label-meta"><span class="label-key">{{ row.key }}</span><span class="label-default">{{ t('adminAgentLabels.default') }}{{ row.default || t('adminAgentLabels.empty') }}</span></div><div class="label-input-wrap"><input v-model="row.custom" :placeholder="row.default || t('adminAgentLabels.emptyDefault')" class="label-input"><button v-if="row.custom" class="label-reset" :title="t('adminAgentLabels.restore')" @click="reset(row)">×</button></div></div></div><div class="labels-group-title">{{ t('adminAgentLabels.tools') }}（{{ filteredTools.length }}/{{ stateLabels.tools.length }}）<input v-model="labelsFilter" :placeholder="t('adminAgentLabels.filterPlaceholder')" class="labels-filter"></div><div class="labels-list"><div v-for="row in filteredTools" :key="row.key" class="label-row"><div class="label-meta"><span class="label-key">{{ row.key }}</span><span class="label-default">{{ t('adminAgentLabels.default') }}{{ row.default }}</span></div><div class="label-input-wrap"><input v-model="row.custom" :placeholder="row.default" class="label-input"><button v-if="row.custom" class="label-reset" :title="t('adminAgentLabels.restore')" @click="reset(row)">×</button></div></div></div><div class="labels-save-bar"><span v-if="labelsSaved" class="labels-saved-tip">{{ t('adminAgentLabels.saved') }}</span><button class="btn-primary" :disabled="labelsSaving" @click="save">{{ labelsSaving ? t('adminAgentLabels.saving') : t('adminAgentLabels.save') }}</button></div></template></section>
</template>
<script setup lang="ts">
import { onMounted } from 'vue'
import { useStateLabels } from '../useStateLabels'
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
const { stateLabels, labelsLoading, labelsSaving, labelsFilter, labelsSaved, filteredTools, refresh, save, reset } = useStateLabels()
onMounted(refresh)
</script>
<style scoped>
.config-card{background:rgba(255,255,255,.05);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:22px 24px;color:rgba(255,255,255,.82)}.card-head{display:flex;align-items:center;gap:13px;margin-bottom:20px}.card-head h3{font-size:14px}.card-head p{font-size:12px;color:rgba(255,255,255,.38);margin-top:2px}.labels-tip{display:flex;gap:8px;margin-bottom:16px;padding:10px 13px;background:rgba(120,170,255,.09);border:1px solid rgba(120,170,255,.22);border-radius:10px;font-size:12.5px;line-height:1.6}.labels-tip code{font-family:monospace;background:rgba(0,0,0,.3);border-radius:5px;padding:1px 6px;color:#ffd9a8}.labels-group-title{display:flex;align-items:center;gap:10px;margin:18px 2px 8px;font-size:12px;color:rgba(255,255,255,.42)}.labels-filter{margin-left:auto;width:180px;background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.1);border-radius:7px;padding:5px 9px;color:#e6e7f0;font-size:12px}.labels-list{display:grid;grid-template-columns:1fr 1fr;gap:8px 14px}.label-row{display:flex;align-items:center;gap:10px;padding:8px 10px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.06);border-radius:9px}.label-meta{display:flex;flex-direction:column;gap:1px;min-width:0;flex:0 0 40%}.label-key{font-size:12px;color:#cdd0e4;font-family:monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label-default{font-size:10.5px;color:rgba(255,255,255,.3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label-input-wrap{position:relative;flex:1;min-width:0}.label-input{width:100%;box-sizing:border-box;background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.1);border-radius:7px;padding:6px 26px 6px 9px;color:#e6e7f0;font-size:12.5px}.label-reset{position:absolute;right:4px;top:50%;transform:translateY(-50%);width:18px;height:18px;border:0;background:rgba(255,255,255,.08);color:rgba(255,255,255,.55);border-radius:50%;cursor:pointer}.labels-save-bar{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:18px;padding-top:14px;border-top:1px solid rgba(255,255,255,.07)}.labels-saved-tip{font-size:12.5px;color:#7fd6a0}.btn-primary{padding:6px 16px;border:0;border-radius:9px;background:linear-gradient(135deg,#7b7fb2,#9590c4);color:#fff;font-size:13px;font-weight:600}.btn-primary:disabled{opacity:.5}.placeholder-panel{padding:12px;color:rgba(255,255,255,.45)}@media(max-width:720px){.labels-list{grid-template-columns:1fr}}
</style>
